// <auto-generated />
using System;
using MagicVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240229021456_UpdateForeignKeyForVillaNumber")]
    partial class UpdateForeignKeyForVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Villa 1 Amenity",
                            CreatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1658),
                            Details = "Villa 1 Details",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 1",
                            Occupancy = 4,
                            Rate = 100.0,
                            Sqft = 1000,
                            UpdatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1672)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Villa 2 Amenity",
                            CreatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1675),
                            Details = "Villa 2 Details",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 2",
                            Occupancy = 6,
                            Rate = 200.0,
                            Sqft = 2000,
                            UpdatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1676)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Villa 3 Amenity",
                            CreatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1679),
                            Details = "Villa 3 Details",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 3",
                            Occupancy = 8,
                            Rate = 300.0,
                            Sqft = 3000,
                            UpdatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1680)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Villa 4 Amenity",
                            CreatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1684),
                            Details = "Villa 4 Details",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 4",
                            Occupancy = 10,
                            Rate = 400.0,
                            Sqft = 4000,
                            UpdatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1685)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Villa 5 Amenity",
                            CreatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1687),
                            Details = "Villa 5 Details",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 5",
                            Occupancy = 12,
                            Rate = 500.0,
                            Sqft = 5000,
                            UpdatedAt = new DateTime(2024, 2, 29, 9, 14, 54, 589, DateTimeKind.Local).AddTicks(1687)
                        });
                });

            modelBuilder.Entity("MagicVilla.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("villaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("villaId");

                    b.ToTable("VillasNumber");
                });

            modelBuilder.Entity("MagicVilla.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("villaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
