using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MagicVilla.Migrations
{
    /// <inheritdoc />
    public partial class AddAutoGeneratedDate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CreatedAt",
                table: "villas");
            migrationBuilder.DropColumn(
                name: "UpdatedAt",
                table: "villas");

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "villas",
                nullable: false,
                defaultValue: DateTime.UtcNow);

            migrationBuilder.AddColumn<DateTime>(
                name: "UpdatedAt",
                table: "villas",
                nullable: false,
                defaultValue: DateTime.UtcNow);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "UpdatedAt",
                table: "villas");

            migrationBuilder.AddColumn<DateTime>(
                name: "CreatedAt",
                table: "villas",
                nullable: false,
                defaultValue: DateTime.UtcNow);
        }
    }
}
